#!/usr/bin/env bash

set -x

if [[ ${TAILSCALE_ENABLE:=false} != true ]]; then
    exit 0
fi

accept_dns=${TAILSCALE_ACCEPT_DNS:-false}
tailscale_hostname=${TAILSCALE_HOSTNAME:-${VIRTUAL_HOST:-pi.hole}}

declare -a args=(${TAILSCALE_ARGS:=})

args+=("--accept-dns=${accept_dns}")
args+=("--hostname=${tailscale_hostname}")

if [[ -n ${TAILSCALE_AUTHKEY} ]]; then
    args+=("--authkey=${TAILSCALE_AUTHKEY}")
fi

# shellcheck disable=SC2068
tailscale up ${args[@]}
