#!/bin/bash


if [[ ${TAILSCALE_ENABLE:=false} != true ]]; then
    s6-svc -O .
    exit 0
fi

declare -a args=(${TAILSCALED_ARGS:=})

exec 2>&1
# shellcheck disable=SC2068
exec tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/var/run/tailscale/tailscaled.sock ${args[@]}
